version: '3.2'
services:
  mysql-server:
    image: mysql:5.7.22
    container_name: mysql_raptorVue
    volumes:
     - ./MySQL/etc/:/etc/mysql/conf.d
     - ./MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=raptorvue
